export NEXT_PUBLIC_SITE_NAME=femdomchat
export NEXT_PUBLIC_API_URL=https://chatcommonapigw.online/api
export NEXT_PUBLIC_FIREBASE_API_KEY="AIzaSyBuDC9HOlUPrRhslnnydqZx2VeYt4t9XcQ"
export NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN="chat-af3ce.firebaseapp.com"
export NEXT_PUBLIC_FIREBASE_PROJECT_ID="chat-af3ce"
export NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET="chat-af3ce.firebasestorage.app"
export NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID="516214182594"
export NEXT_PUBLIC_FIREBASE_APP_ID="1:516214182594:web:50a5a96b1b0fde0671a15b"
export NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID="G-7RYZS49T6M"
npm run dev
